
CREATE TABLE regiao (
  id INT(11) NOT NULL AUTO_INCREMENT,
  codigo NUMERIC,
  nome VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE municipio (
  id INT(11) NOT NULL AUTO_INCREMENT,
  id_regiao INT(11) NOT NULL,
  nome VARCHAR(255) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (id_regiao) REFERENCES regiao(id)
);
